config/routes.rb
GlbWebApp::Application.routes.draw do

  root :to => 'home#index'

  get 'providers_confirm' => 'home#providers_confirm'
  get 'new_mailing' => 'home#new_mailing'
  get 'mailing_list' => 'home#mailing_list'
  get 'schedule_batch_1' => 'home#schedule_batch_1'
  get 'schedule_batch_2' => 'home#schedule_batch_2'
  get 'job_preview' => 'home#job_preview'

	# part 2

  get 'new_mailing_confirm' => 'home#new_mailing_confirm'
  get 'inbox/list' => 'home#inbox_list'
  get 'inbox/grid' => 'home#inbox_grid'
  get 'received' => 'home#received'
  get 'providers' => 'home#providers'
  get 'login/1' => 'home#login_1'
  get 'login/2' => 'home#login_2'

  # part 3

  get 'profile' => 'home#profile'
  get 'new_address' => 'home#new_address'
  get 'new_address_confirm' => 'home#new_address_confirm'
  get 'change_password' => 'home#change_password'
  get 'edit_name' => 'home#change_name'
  get 'preferences' => 'home#preferences'
  get 'notifications' => 'home#notifications'
  get 'add_filter' => 'home#add_filter'
  get 'edit_filter' => 'home#edit_filter'

  get 'new_header' => 'home#new_header'

  # part4
  get 'address' => 'home#address'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
		@title = "Index"
		@header_icons = true
	end

	def providers_confirm
		@breadcrumbs = ["Home", "Preferences", "Providers"]
		@title = "Confirmation"
	end

	def new_mailing
		@breadcrumbs = ["Home", "New mailing"]
		@title = "New mailing"
	end

	def mailing_list
		@breadcrumbs = ["Home", "Mailing list"]
		@title = "Mailing list"
	end

	def schedule_batch_1
		@breadcrumbs = ["Home", "Mailing list", "Schedule batches"]
		@title = "Schedule batch"
	end

	def schedule_batch_2
		@breadcrumbs = ["Home", "Mailing list", "Schedule batches"]
		@title = "Schedule batch"
	end

	def job_preview
		@breadcrumbs = ["Home", "Mailing list", "Mailing #01"]
		@title = "Mailing #01"
	end

	# part 2

	def new_mailing_confirm
		@breadcrumbs = ["Home", "New mailing"]
		@title = "New mailing"
	end

	def inbox_list
		@breadcrumbs = ["Home", "Inbox", "Banks"]
		@title = "Inbox"
	end

	def inbox_grid
		@breadcrumbs = ["Home", "Inbox", "Banks"]
		@title = "Inbox"
	end

	def received
		@breadcrumbs = ["Home", "Inbox", "Received", "Sample title"]
		@title = "Received"
	end

	def providers
		@breadcrumbs = ["Home", "Preferences", "Providers"]
		@title = "Providers list"
	end

	def login_1
		@title = "Login"
	end

	def login_2
		@title = "Login"
	end

	# part 3

	def profile
		@breadcrumbs = ["Home", "Preferences", "Profile"]
		@title = "Profile"
	end

	def new_address
		@breadcrumbs = ["Home", "Profile", "New postal addresses"]
		@title = "Postal addresses"
	end

	def new_address_confirm
		@breadcrumbs = ["Home", "Profile", "New postal addresses"]
		@title = "Postal addresses"
	end

	def change_password
		@breadcrumbs = ["Home", "Profile", "Change password"]
		@title = "Password"
	end

	def change_name
		@breadcrumbs = ["Home", "Profile", "Edit name"]
		@title = "Edit name"
	end

	def preferences
		@breadcrumbs = ["Home", "Preferences"]
		@title = "Preferences"
	end

	def notifications
		@breadcrumbs = ["Home", "Partials"]
		@title = "Notifications"
	end

	def add_filter
		@breadcrumbs = ["Home", "Preferences", "Add filter"]
		@title = "Add filter"
	end

	def edit_filter
		@breadcrumbs = ["Home", "Preferences", "Edit filter"]
		@title = "Edit filter"
	end

	def new_header
		@new_menu = true
  end

  # part 3

  def address
    @breadcrumbs = ["Home", "Address"]
    @title = "Address"

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_edit_filter.html.haml
%h3.page-title Edit filter
.light-spacer.margin-bottom-50

%form

	.row.margin-bottom-30
		.span3
			.control-group.form-group
				%label Filter name:
				.controls
					%input.input-fit-box{:type=>'text'}
			.control-group.form-group
				%label Opened:
				.controls
					%select.input-fit-box.select-ui
						%option Both
						%option Opened
						%option Not opened
			.control-group.form-group
				%label Paid:
				.controls
					%select.input-fit-box.select-ui
						%option Not available or both
						%option Paid
						%option Not paid
		.span3
			.control-group.form-group
				%label Tags

				.selectable-list.show-6
					- iterator = 0
					- 10.times do
						- iterator = iterator + 1
						
						%label{:for => "selectable_b_#{iterator}"}
							Tagname
							= iterator  
						- if (iterator-1)%3 == 0
							%input.selectable-ui{:type=>'checkbox', :checked=>'checked', :id=>"selectable_b_#{iterator}"}
						- else
							%input.selectable-ui{:type=>'checkbox', :id=>"selectable_b_#{iterator}"}
		.span3
			.control-group.form-group
				%label Providers:

				.selectable-list.show-6
					- iterator = 0
					- 10.times do
						- iterator = iterator + 1
						
						%label{:for => "selectable_c_#{iterator}"}
							Provider
							= iterator  
						- if iterator%3 == 0
							%input.selectable-ui{:type=>'checkbox', :checked=>'checked', :id=>"selectable_c_#{iterator}"}
						- else
							%input.selectable-ui{:type=>'checkbox', :id=>"selectable_c_#{iterator}"}

		.span3
			.control-group.form-group
				%label Other users:
				.controls
					%select.input-fit-box.select-ui
						%option None
			.control-group.form-group
				%label Search term:
				.controls
					%input.input-fit-box{:type=>'text'}

		.clearfix

	.action-buttons
		%a.btn.btn-auto-width.btn-wider{:href=>'#'} Cancel
		%button.btn.btn-primary.btn-wider.btn-auto-width{:type=>'submit'} Save filter

app/views/home/_page_head.html.erb
<div class="page-head">
	<div class="container">
		<div class="row">
			<div class="span12">
				<h1><%= @title %></h1>
				<div class="buttons">
					<a href="#" class="btn"><i class="icon-white-mail"></i>Mail</a>
					<a href="#" class="btn"><i class="icon-white-profile"></i>Account</a>
					<a href="#" class="btn"><i class="icon-white-settings"></i>Preferences</a>
					<input type="text" class="btn input-icon-white-zoom" value="What are you looking for?" />
				</div>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
</div>

app/views/home/_password.html.erb
<div class="step">Step 2 of 2</div>
<div class="sign-up-container">
    <div class="form-body">
      <form>
      	<div class="form-group password">
	        <label>Password</label>
	        <div class="password-table">
	          <table>
	            <tbody><tr class="letters">
	              <td class="icon"><div><img src="<%= asset_path 'images/key.png' %>"></div></td>
	              <td><input type="text"></td>
	              <td><input type="text" disabled="disabled"></td>
	              <td><input type="text"></td>
	              <td><input type="text" disabled="disabled"></td>
	              <td><input type="text"></td>
	              <td><input type="text" disabled="disabled"></td>
	              <td><input type="text"></td>
	              <td><input type="text"></td>
	              <td><input type="text"></td>
	              <td><input type="text"></td>
	              <td><input type="text"></td>
	              <td><input type="text"></td>
	              <td><input type="text"></td>
	              <td><input type="text"></td>
	              <td><input type="text"></td>
	              <td><input type="text"></td>
	              <td><input type="text"></td>
	              <td><input type="text"></td>
	              <td><input type="text"></td>
	              <td><input type="text"></td>
	              <td><input type="text"></td>
	              <td><input type="text"></td>
	            </tr>
	            <tr class="legend">
	              <td></td>
	              <td>1</td>
	              <td>2</td>
	              <td>3</td>
	              <td>4</td>
	              <td>5</td>
	              <td>6</td>
	              <td>7</td>
	              <td>8</td>
	              <td>9</td>
	              <td>10</td>
	              <td>11</td>
	              <td>12</td>
	              <td>13</td>
	              <td>14</td>
	              <td>15</td>
	              <td>16</td>
	              <td>17</td>
	              <td>18</td>
	              <td>19</td>
	              <td>20</td>
	              <td>21</td>
	              <td>22</td>
	            </tr>
	          </tbody></table>
	          <p><a href="#" class="pull-right password-remind">I forgot my password</a></p>
	          <div class="clearfix"></div>
	        </div>
	    </div>
	    <p class="text-center"><input type="submit" value="Next" class="btn btn-primary btn-wider"></p>
	    <div class="clearfix"></div>
      </form>
    </div>
</div>

app/views/home/change_name.haml
= render :partial => 'page_head'

.main
	.container
		= render :partial => 'breadcrumbs'


		.row
			.span12

				%h1.page-title Change your name

				.light-spacer
				.row
					.span12
						.lead
							%p 
								Change your name. This will be your official mail name to post delivery. You are not allowed to forward your account to another person and it's against terms and conditions. If we detect such abuse account will be locked. You can use 'link account' feature to read somebodys email.


				%form
					.row.margin-bottom-30
						.span2
							.form-group
								%label Title:
								.control-group
									%select.full-width-select.select-ui
										%option Mr
										%option Ms
						.span2
							.form-group
								%label First name:
								.control-group
									%input.full-width-input{:type=>"text"}
						.span2
							.form-group
								%label Second name (opt.):
								.control-group
									%input.full-width-input{:type=>"text"}
						.span2
							.form-group
								%label Suffix (opt.):
								.control-group
									%select.full-width-select.select-ui
										%option Jnr
										%option Snr
						.span2
							.form-group
								%label Last name:
								.control-group
									%input.full-width-input{:type=>"text"}

					.action-buttons
						%a.btn{:href=>'#'} Cancel
						%button.btn.btn-primary.btn-auto-width.btn-wider{:type=>"submit"} Change name

app/views/home/index.html.haml
= render :partial => 'page_head'
.main
	.container
		.row
			.span4.offset4
				%ul.nav
					%li
						= link_to "New mailing", new_mailing_path
					%li
						= link_to "Mailing list", mailing_list_path
					%li
						= link_to "Job preview", job_preview_path
					%li
						= link_to "Providers confirm", providers_confirm_path
					%li
						= link_to "schedule batch 1/2", schedule_batch_1_path
					%li
						= link_to "schedule batch 2/2", schedule_batch_2_path
				%ul.nav
					%li
						= link_to "New mailing confirm", new_mailing_confirm_path
					%li
						= link_to "Inbox list", inbox_list_path
					%li
						= link_to "Inbox grid", inbox_grid_path
					%li
						= link_to "Received", received_path
					%li
						= link_to "Providers", providers_path
					%li
						= link_to "Login step 1", login_1_path
					%li
						= link_to "Login step 2", login_2_path
				%ul.nav
					%li
						= link_to "Profile", profile_path
					%li
						= link_to "New address", new_address_path
					%li
						= link_to "New address confirm", new_address_confirm_path
					%li
						= link_to "Change password", change_password_path
					%li
						= link_to "Edit name", edit_name_path
					%li
						= link_to "Preferences", preferences_path
					%li
						= link_to "Add filter", add_filter_path
					%li
						= link_to "Edit filter", edit_filter_path

				%ul.nav
					%li
						Additional:
						%ul
							%li
								= link_to "Notifications", notifications_path
							%li
								= link_to "New header", new_header_path

app/views/home/login_1.html.haml
= render :partial => 'page_head'

.main.form-page
	.container
		= render :partial => 'breadcrumbs'


		.row
			.span12
				
				.login-wrapper.span4
					= render :partial => 'login'

app/views/home/new_address.haml
= render :partial => 'page_head'

.main
	.container
		= render :partial => 'breadcrumbs'


		.row
			.span12

				%h1.page-title New postal address

				.light-spacer
				.row
					.span9
						.lead
							%p 
								This is a page where you can change delivery address for mail that will be send to you through snail mail. We will send you paper mail with verification code on new address to confirm that you indeed occupy address you provided. You can change your address once a month.


				%form
					.row.margin-bottom-30
						.span3
							.form-group
								%label Country:
								.control-group
									%select.input-fit-box.select-ui
										%option Ireland
										%option England

						.span5
							.form-group
								%label Address:
								.control-group
									%input.input-fit-box{:placeholder => 'Put your new postal address here', :type=>'text'}

					.action-buttons
						%a.btn{:href=>'#'} Cancel
						%button.btn.btn-primary.btn-auto-width.btn-wider{:type=>"submit"} Add address

app/views/home/new_address_confirm.html.haml
= render :partial => 'page_head'

.main
	.container
		= render :partial => 'breadcrumbs'


		.row
			.span12

				%h1.page-title Thank you!

				.light-spacer

				.lead
					%p 
						We are sending you paper mail on address you provided. After you receive it, come back to our website, login to your account and confirm your new address with a verification code from the mail.

					%p
						After that we will be able to provide digital mail service for you.

				%p
					%a.btn.btn-primary.btn-wider{:href=>"#"} Go to Homepage

app/views/home/new_header.html.haml
.home-promo
	.home-promo-background
		= image_tag asset_path "images/home_promo.jpg"

	.container
		.row
			.span12
				.home-promo-inner
					.home-promo-wrapper
						%h2.home-promo-title
							Every home in Ireland now has a
							%br
							%strong Digital Postbox
						%p 
							Receive mail and pay bills from selected providers and securely store 
							%br
							important documents online, in one place and with one password. 
						%p
							%a.btn.btn-primary{:href=>'#'} Claim Your Address Today!
						%p
							%a{:href=>'#'}
								= image_tag asset_path "images/home_video.jpg"
							%br
							%small See how it all works
.main
	.container
		.row
			.span12
				%h3.page-title Lorem ipsum
				.light-spacer

app/views/home/new_mailing.html.haml
= render :partial => 'page_head'

.main
	.container
		= render :partial => 'breadcrumbs'


		.row
			.span12

				%h1.page-title Create new mailing

				.light-spacer

				.lead
					%p In order to create new mailing you need to supply address database in metadata format and content to be send to addressie.


				.row
					%table.table-upload-row.span6.table-center.table-padding
						%tr
							%td.bordered-cell-left
								%strong Metadata (XML format):
							%td.bordered-cell-right.background-cell.file-cell
								%div
									%span.mask{:style=>'width: 68%'} 68%
									No file uploaded
							%td
								%a.btn.btn-primary.file-upload-trigger Choose file
					%table.table-upload-row.span6.table-center.table-padding
						%tr
							%td.bordered-cell-left

								%strong Mailing content (PDF format):
							%td.bordered-cell-right.background-cell.file-cell
								%div
									%span.mask
									No file uploaded
							%td
								%a.btn.btn-primary.file-upload-trigger Choose file
					.clearfix	



				.action-buttons
					%a.btn{:href=>"#"} Cancel
					%a.btn.btn-primary{:href=>"#"} Create mailing

app/views/home/providers_confirm.html.haml
= render :partial => 'page_head'

.main
	.container
		= render :partial => 'breadcrumbs'


		.row
			.span12

				%h1.page-title Paper billers list summary

				.light-spacer

				.lead
					%p This is a list of providers that you selected to receive paper mail from. Please conform list with a button below.


				.row
					%table.table-simple.table-two-coloured.table-bordered.table-center.span6
						%tr
							%td 
								%strong Provider name
							%td 
								%strong Provider group
						%tr
							%td
								ACC Bank
							%td
								%i.icon-banks
								Banks
						%tr
							%td
								Allied Irish Bank
							%td
								%i.icon-banks
								Banks
						%tr
							%td
								Bank of Ireland
							%td
								%i.icon-banks
								Banks

					.clearfix	



				.action-buttons
					%a.btn{:href=>"#"} Cancel
					%a.btn.btn-primary{:href=>"#"} Confirm list

app/views/home/received.html.haml
= render :partial => 'page_head'

.main
	.container
		.row
			.span9
				= render :partial => 'breadcrumbs'
			.quick-action-bar.span3
				%a{:href=>'#'}
					%i.icon-list-view
				%a{:href=>'#'}
					%i.icon-quick-print
				%a{:href=>'#'}
					%i.icon-quick-download
			.clearfix

		.row
			.span12
				.row
					.span5.envelopes-grid-onecolumn
						.envelopes-grid.envelopes-grid-onecolumn.scrollarea
							%a.mail{:href=>"#"}
								.provider
									= image_tag asset_path 'images/provider_logo/ebay.png'
								.text
									%p 
										Sample title
										%br
										Lorem ipsum dolor
								.stamp
									%span 11.05.2013
								.status
									%span.green Paid
									%br
									%span.green Opened: 15.05.2013
							%a.active.mail{:href=>"#"}
								.provider
									= image_tag asset_path 'images/provider_logo/electric.png'
								.text
									%p 
										Demo User
										%br
										Sample Street 1234
										%br
										Dublin 4
								.stamp
									%span 11.05.2013
								.status
									%span.red Not paid
									%br
									%span.green Opened: 15.05.2013
							%a.mail{:href=>"#"}
								.provider
									= image_tag asset_path 'images/provider_logo/electric.png'
								.text
									%p 
										Demo User
										%br
										Sample Street 1234
										%br
										Dublin 4
								.stamp
									%span 11.05.2013
								.status
									%span.red Not paid
									%br
									%span.green Opened: 15.05.2013
							%a.mail{:href=>"#"}
								.provider
									= image_tag asset_path 'images/provider_logo/ebay.png'
								.text
									%p 
										Sample title
										%br
										Lorem ipsum dolor
								.stamp
									%span 11.05.2013
								.status
									%span.green Paid
									%br
									%span.green Opened: 15.05.2013
							%a.mail{:href=>"#"}
								.provider
									= image_tag asset_path 'images/provider_logo/electric.png'
								.text
									%p 
										Demo User
										%br
										Sample Street 1234
										%br
										Dublin 4
								.stamp
									%span 11.05.2013
								.status
									%span.red Not paid
									%br
									%span.green Opened: 15.05.2013
							%a.mail{:href=>"#"}
								.provider
									= image_tag asset_path 'images/provider_logo/electric.png'
								.text
									%p 
										Demo User
										%br
										Sample Street 1234
										%br
										Dublin 4
								.stamp
									%span 11.05.2013
								.status
									%span.red Not paid
									%br
									%span.green Opened: 15.05.2013
								

					.span7
						.pdf-preview
							.toolbar

							.content
								= image_tag asset_path 'images/pdf-preview.png'

						.action-buttons
							.pull-right
								%span.btn.red-button.btn-disabled
									%i.icon-white-not-paid
									Not paid
								%a.btn.green-button{:href=>"#"}
									%i.icon-white-pay-now
									Pay now

					.clearfix

app/views/home/schedule_batch_1.html.haml
= render :partial => 'page_head'

.main
	.container
		= render :partial => 'breadcrumbs'


		.row
			.span12

				%h1.page-title Schedule batches for mailing 1/2

				.light-spacer

				.lead
					%p In order to arrange batches answer our two questions:

				%form
					.row
						.span4
							.form-group
								%label How many records will be send per batch?
								%input.form-control{:type=>"text", :value => "30000"}
						.span4
							.form-group
								%label Choose frequency of the batches:
								%select.select-ui
									%option Every two days
									%option Once a week



				.action-buttons
					%a.btn{:href=>"#"} Cancel
					%button.btn.btn-primary.btn-wider.btn-auto-width{:type=>"submit"} Arrange batches

app/views/layouts/_footer.html.erb
            <div id="footer">
	<div class="container">
		<div class="row">
			<div class="span2">
				<ul class="nav">
					<li class="list-head">Main</li>
					<li><a href="/">Start Here</a></li>
					<li><a href="/overview">Easy set up</a></li>
					<li><a href="/features">Features</a></li>
					<li><a href="/help">Help</a></li>
				</ul>
			</div>
			<div class="span2">
				<ul class="nav">
					<li class="list-head">Client area</li>
					<li><a href="/register/">Sign up</a></li>
					<li><a href="/login">Login</a></li>
					<li><a href="/contact">Contact us</a></li>
				</ul>
			</div>
			<!--<div class="span2">
				<ul class="nav">
					<li class="list-head">Get App</li>
					<li><a href="#">App Store</a></li>
					<li><a href="#">Google Play</a></li>
				</ul>
			</div>-->
			<!-- 
			<div class="span6">
				<div class="social">
					<a class="twitter">twitter</a>
					<a class="facebook">facebook</a>
				</div>
			</div>
			 -->
		</div>
		<div class="copyright">
			&copy; GreenLetterbox Ltd.<br />
			<a href="/privacy">Privacy Policy</a> | <a href="/terms">Terms of Service</a>
		</div>
	</div>
</div>        

    <!--[if lte IE 9]> 
    <script type="text/javascript" src="ie.js"></script>
    <![endif]-->

app/views/layouts/_header.html.erb
<% if @new_menu.nil? %>
  <div class="navbar navbar-static-top navbar-white">
    <div class="navbar-inner">
      <div class="container">
        <div class="row">
          <div class="span12">


            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              Menu
              <span class="icon-chevron-down menu-caret"></span>
            </button>
            <a class="brand" href="<%= root_path %>">
              <img src="<%= asset_path "images/logo-bigger.png" %>" />
            </a>
            <div class="nav-collapse collapse">
              <ul class="nav nav-login">
                <% unless @header_icons.nil? %>
                  <li><a href="/register/"><i class="icon-mailing icon-white"></i> Mailing</a></li>
                <% end %>
                <li><a href="/register/"><i class="icon-header-user icon-white"></i> Sign up</a></li>
                <li><a href="#"><i class="icon-header-lock icon-white"></i> Login</a></li>
                <% unless @header_icons.nil? %>
                <li><a href="#"><i class="icon-header-lockout icon-white"></i> Logout</a></li>
                <% end %>
              </ul>
              <div class="clearfix"></div>
              <ul class="main-menu nav">
                <li><a href="#">Overview</a></li>
                <li><a href="#">Set up</a></li>
                <li><a href="#">Features</a></li>
                <li><a href="#">Environment</a></li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Contact</a></li>
              </ul>
            </div><!--/.nav-collapse -->
          
          </div>
        </div>
      </div>
    </div>
  </div>

<% else %>


<!-- new header -->

  <div class="navbar new-navbar navbar-static-top navbar-white">
    <div class="navbar-inner">
      <div class="container">
        <div class="row">
          <div class="span12">


            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
              Menu
              <span class="icon-chevron-down menu-caret"></span>
            </button>
            <div class="brand-container">
              <a class="beta" href="#"><img src="<%= asset_path "images/beta.png" %>" /></a>
              <a class="brand" href="<%= root_path %>">
                <img src="<%= asset_path "images/logo.png" %>" />
              </a>
            </div>
            <div class="nav-collapse collapse">
              <ul class="nav nav-login">
                <li><a href="/register/"><i class="icon-header-address"></i> Claim your address</a></li>
                <li><a href="#">
                  <i class="icon-header-profile"></i>
                  Login
                </a></li>
              </ul>
              <ul class="main-menu nav">
                <li class="active"><a href="#">Setup</a></li>
                <li><a href="#">Features</a></li>
                <li><a href="#">Environment</a></li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Contact</a></li>
              </ul>
            </div><!--/.nav-collapse -->
          
          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GlbWebApp</title>
  <meta name="viewport" content="width=device-width, initial-scale=0.8">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,400,300,600" rel="stylesheet" type="text/css">
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  <%= csrf_meta_tags %>
	<!--[if lte IE 8]> 
	  <%= stylesheet_link_tag    "ie", :media => "all" %>
	<![endif]--> 
</head>
<body>

	<%= render :partial => '/layouts/header' %>

	<%= yield %>

	<%= render :partial => '/layouts/footer' %>

</body>
</html>